language: node_js

node_js:
  - "0.12"

install:
  # install pm2
  - npm -g install pm2

services:
  - mongodb

env:
  global:
    - export MONGO_URL='mongodb://127.0.0.1:27017/pmteor'
    - export ROOT_URL='https://example.com'
    - export ADMIN='user:pass@domain.com'
    - export BUNDLE_DIR='/home/travis/bundles'
    - export PORT=3000

notifications:
  slack: pmteorteam:2CrW3i59qe4FeHfN7rjBl9dj

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$HOME/.meteor:$PATH

script:
  - meteor build --directory ../build
  - cd ../build
  - (cd bundle/programs/server && npm install)
  - (cd bundle/programs/server/npm && rm -rf bcrypt)
  # install bcrypt globally (trying to circumvent a bug in bundled version)
  - (cd bundle/programs/server && npm install bcrypt)
  - pm2 start bundle/main.js
  # give Meteor some time to init data, and to start
  - sleep 15
  - cat ~/.pm2/logs/*
