language: node_js

node_js:
  - "0.12"

install:
  - npm -g install pm2

services:
  - mongodb

env:
  global:
    - export ROOT_URL='https://example.com'
    - export ADMIN='user:pass@domain.com'
    - export BUNDLE_DIR='/home/travis/bundles'
    - export PORT=3000

notifications:
  slack: pmteorteam:2CrW3i59qe4FeHfN7rjBl9dj

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$HOME/.meteor:$PATH

script:
  - meteor build --directory ../build
  - cd ../build
  - cd bundle/programs/server
  - npm install
