language: node_js

node_js:
  - "0.12"

notifications:
  slack: pmteorteam:2CrW3i59qe4FeHfN7rjBl9dj

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$HOME/.meteor:$PATH

before_script:
  - export ADMIN='user:pass@test.com'
  - export BUNDLE_DIR='.'

script:
  - meteor run
